### ISSUE TITLE
 failed to build to retaddrspoof.asm to an object file

### ISSUE THREAD

**Issue by ettorhake** [cpu0x00/Ghost#5]
[i] command used: /usr/bin/nasm -f win64 retaddrspoof.asm -o retaddrspoof.o

i can't build .asm file, don't know why, do you have a idea ?

**Comment by cpu0x00** [comment]
can you run the command provided and give me the error produced by nasm? 
`/usr/bin/nasm -f win64 retaddrspoof.asm -o retaddrspoof.o`

also make sure that you have nasm and the MinGW suite installed

```
apt install nasm mingw-w64
```

**Comment by ettorhake** [comment]
already installed : 

mingw-w64 is already the newest version (7.0.0-2).
nasm is already the newest version (2.14.02-1).

NASM Error : 

retaddrspoof.asm:25: error: invalid combination of opcode and operands

**Comment by cpu0x00** [comment]
![image](https://github.com/user-attachments/assets/e9168752-9094-48c8-8544-8e64fc93eddf)

i cloned the repo from scratch and tested the build 

if you can provide me with more information about your system to try and understand the root cause ?

**Comment by ettorhake** [comment]
strange. My sys : #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpu0x00** [comment]
![image](https://github.com/user-attachments/assets/9e531b0b-37c4-4455-a434-60a3c62c8a2e)

i spun up an ubuntu machine to test it as well, can you try to reclone and see if it still persists

and also , the nasm version i used on both my machine and the ubuntu is:
```
nasm --version
NASM version 2.16.01
```

**Comment by ettorhake** [comment]
thanks @cpu0x00 im trying to update and test
