### ISSUE TITLE
Can`t online

### ISSUE THREAD

**Issue by shannaburns** [cpu0x00/Ghost#7]
I switched to 4.9.1 or 4.8 with no profile and udrl, and it won’t crash anymore, but it keeps looping and sleeping. Why is it not online?
![image](https://github.com/user-attachments/assets/f7f3bb08-38e0-4e0d-9fb2-6dece4f9dea9)

**Comment by cpu0x00** [comment]
this means its working as it should , if its not reaching out to you this sounds like an issue in your network topology not with the loader
